"""Generate production clean resource pages and their catalog-driven sitemap."""

from __future__ import annotations

import shutil
from html import escape
from pathlib import Path

from catalog_lib import REPOSITORY_ROOT, load_resources, load_site, load_taxonomy, taxonomy_indexes, validate_catalog
from shadow_catalog import absolute_url, published_resources, sitemap_paths, topic_records
from static_resource_pages import SHADOW_ROOT, generate as generate_shadow_pages


PRODUCTION_RESOURCE_ROOT = REPOSITORY_ROOT / "resources"
PRODUCTION_STYLESHEET = REPOSITORY_ROOT / "resource-pages.css"
PRODUCTION_SCRIPT = REPOSITORY_ROOT / "resource-pages.js"
PRODUCTION_SITEMAP = REPOSITORY_ROOT / "sitemap.xml"
CRAWLABLE_INDEX_PAGE = REPOSITORY_ROOT / "worksheets.html"
CRAWLABLE_INDEX_START = "<!-- BEGIN GENERATED CRAWLABLE SITE INDEX -->"
CRAWLABLE_INDEX_END = "<!-- END GENERATED CRAWLABLE SITE INDEX -->"


def _replace_resource_root(source_root: Path, destination_root: Path) -> None:
    resolved = destination_root.resolve()
    expected = (REPOSITORY_ROOT / "resources").resolve()
    if resolved != expected:
        raise ValueError(f"Unsafe production resource output path: {resolved}")
    if resolved.exists():
        shutil.rmtree(resolved)
    shutil.copytree(source_root, resolved)


def _sitemap_paths() -> list[str]:
    site, taxonomy, resources = load_site(), load_taxonomy(), load_resources()
    validate_catalog(site, taxonomy, resources)
    published = published_resources(resources)
    indexes = taxonomy_indexes(taxonomy)
    topics = topic_records(published, taxonomy, indexes, site)
    return sitemap_paths(published, topics, taxonomy, site)


def _write_sitemap(paths: list[str]) -> int:
    site = load_site()
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        *[f"  <url><loc>{escape(absolute_url(site, path))}</loc></url>" for path in paths],
        "</urlset>",
    ]
    PRODUCTION_SITEMAP.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return len(paths)


def _write_crawlable_site_index(paths: list[str]) -> int:
    source = CRAWLABLE_INDEX_PAGE.read_text(encoding="utf-8")
    if source.count(CRAWLABLE_INDEX_START) != 1 or source.count(CRAWLABLE_INDEX_END) != 1:
        raise ValueError("worksheets.html must contain one generated crawlable-index block")
    links = []
    for path in paths:
        href = f"/{path}" if path else "/"
        label = path or "Home"
        links.append(f'            <li><a href="{escape(href, quote=True)}">{escape(label)}</a></li>')
    block = "\n".join([
        CRAWLABLE_INDEX_START,
        "<!-- Generated by site-tools/generate_production_resource_pages.py. Do not edit this block by hand. -->",
        "<noscript>",
        '    <nav aria-label="Complete site index">',
        "        <h2>Complete site index</h2>",
        "        <ul>",
        *links,
        "        </ul>",
        "    </nav>",
        "</noscript>",
        CRAWLABLE_INDEX_END,
    ])
    before, remainder = source.split(CRAWLABLE_INDEX_START, 1)
    _, after = remainder.split(CRAWLABLE_INDEX_END, 1)
    CRAWLABLE_INDEX_PAGE.write_text(before + block + after, encoding="utf-8", newline="\n")
    return len(links)


def generate() -> dict:
    manifest = generate_shadow_pages(SHADOW_ROOT)
    _replace_resource_root(SHADOW_ROOT / "resources", PRODUCTION_RESOURCE_ROOT)
    PRODUCTION_STYLESHEET.write_bytes((SHADOW_ROOT / "resource-pages.css").read_bytes())
    PRODUCTION_SCRIPT.write_bytes((SHADOW_ROOT / "resource-pages.js").read_bytes())
    paths = _sitemap_paths()
    sitemap_count = _write_sitemap(paths)
    crawlable_link_count = _write_crawlable_site_index(paths)
    return {
        "resourcePageCount": manifest["publishedResourceCount"],
        "retiredExcludedCount": manifest["retiredResourceCount"],
        "sitemapUrlCount": sitemap_count,
        "crawlableLinkCount": crawlable_link_count,
    }


if __name__ == "__main__":
    result = generate()
    print(
        "PRODUCTION RESOURCE PAGES generated "
        f"pages={result['resourcePageCount']} "
        f"retired_excluded={result['retiredExcludedCount']} "
        f"sitemap={result['sitemapUrlCount']} "
        f"crawlable_links={result['crawlableLinkCount']}"
    )
