"""Generate the synchronous directory.js resource compatibility block from the catalog."""

from __future__ import annotations

import json
from pathlib import Path

from catalog_lib import REPOSITORY_ROOT, load_resources, load_site, load_taxonomy, taxonomy_indexes, validate_catalog
from shadow_catalog import catalog_digest, published_resources


DIRECTORY_PATH = REPOSITORY_ROOT / "directory.js"
START_MARKER = "// BEGIN GENERATED CATALOG COMPATIBILITY DATA"
END_MARKER = "// END GENERATED CATALOG COMPATIBILITY DATA"


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def resource_line(resource: dict, indexes: dict) -> str:
    classification = resource["taxonomy"]
    assets = resource["assets"]
    grade = indexes["grades"][classification["grade"]]["label"]
    subject = indexes["subjects"][classification["subject"]]["label"]
    topic = indexes["topics"][(classification["grade"], classification["subject"], classification["topic"])]["label"]
    skill = indexes["skills"][(classification["grade"], classification["subject"], classification["topic"], classification["skills"][0])]["label"]
    values = [
        ("id", resource["id"]), ("title", resource["title"]),
        ("description", resource["description"]), ("grade", grade),
        ("subject", subject), ("topic", topic), ("skill", skill),
    ]
    fields = [f"{key}:{js_string(value)}" for key, value in values]
    fields.append(f"keywords:{json.dumps(resource['keywords'], ensure_ascii=False, separators=(',', ':'))}")
    fields.extend((
        f"pdfPath:{js_string(assets['bundlePdf'])}",
        f"thumbnailPath:{js_string(assets['previewDirectory'] + '/page-01.png')}",
        f"pageCount:{len(resource['pages'])}",
    ))
    labels = [page.get("label") for page in resource["pages"]]
    if any(labels):
        fields.append(f"pageLabels:{json.dumps(labels, ensure_ascii=False, separators=(',', ':'))}")
    fields.append(
        f"pages:defineWorksheetPages({len(resource['pages'])},{js_string(assets['pagePdfDirectory'])},{js_string(assets['previewDirectory'])})"
    )
    fields.extend((
        f"backHref:{js_string(resource['legacy']['backHref'])}",
        f"backLabel:{js_string(resource['legacy']['backLabel'])}",
    ))
    return "  {" + ",".join(fields) + "},"


def seo_map(name: str, resources: list[dict]) -> list[str]:
    lines = [f"const {name}=Object.freeze({{"]
    for index, resource in enumerate(resources):
        suffix = "," if index < len(resources) - 1 else ""
        lines.append(
            f"  {js_string(resource['id'])}:{{seoTitle:{js_string(resource['seo']['title'])},"
            f"seoDescription:{js_string(resource['seo']['description'])}}}{suffix}"
        )
    lines.append("});")
    return lines


def render_block() -> str:
    site, taxonomy, resources = load_site(), load_taxonomy(), load_resources()
    validate_catalog(site, taxonomy, resources)
    indexes = taxonomy_indexes(taxonomy)
    published = published_resources(resources)
    by_subject = {
        subject: [resource for resource in published if resource["taxonomy"]["subject"] == subject]
        for subject in ("math", "reading-language", "communication-life-skills")
    }
    lines = [
        f"{START_MARKER} sha256={catalog_digest()}",
        "// Generated by site-tools/generate_production_runtime.py. Do not edit this block by hand.",
        "const worksheetResourceDefinitions = [",
        *[resource_line(resource, indexes) for resource in published],
        "];",
        *seo_map("preschoolMathResourceSeoMetadata", by_subject["math"]),
        *seo_map("preschoolReadingResourceSeoMetadata", by_subject["reading-language"]),
        *seo_map("preschoolCommunicationResourceSeoMetadata", by_subject["communication-life-skills"]),
        END_MARKER,
    ]
    return "\n".join(lines)


def replace_block(source: str, generated: str) -> str:
    if START_MARKER in source:
        start = source.index(START_MARKER)
        end = source.index(END_MARKER, start) + len(END_MARKER)
    else:
        start = source.index("const worksheetResourceDefinitions = [")
        end = source.index("const preschoolMathTopicSeoMetadata=", start)
        while end > start and source[end - 1] in "\r\n":
            end -= 1
    return source[:start] + generated + source[end:]


def main() -> None:
    source = DIRECTORY_PATH.read_text(encoding="utf-8")
    updated = replace_block(source, render_block())
    DIRECTORY_PATH.write_text(updated, encoding="utf-8", newline="\n")
    print(f"GENERATED production runtime resources=41 path={DIRECTORY_PATH.name}")


if __name__ == "__main__":
    main()
