const defineWorksheetPages=(pageCount,pdfDirectory,previewDirectory)=>Array.from({length:pageCount},(_,index)=>{
  const number=index+1;
  const filename=`page-${String(number).padStart(2,"0")}`;
  return {number,previewPath:`${previewDirectory}/${filename}.png`,pdfPath:`${pdfDirectory}/${filename}.pdf`};
});
const worksheetResourceDefinitions = [
  {id:"number-recognition-1-5",title:"Number Recognition 1-5",description:"Recognize, find, count, and trace numbers 1-5.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Recognition",keywords:["numbers 1-5","numerals","find","count","trace"],pdfPath:"worksheets/preschool/math/number-recognition/number-recognition-1-5.pdf",thumbnailPath:"thumbnails/preschool/math/number-recognition/number-recognition-1-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/number-recognition/number-recognition-1-5","thumbnails/preschool/math/number-recognition/number-recognition-1-5"),backHref:"number-recognition.html",backLabel:"Back to Number Recognition"},
  {id:"number-recognition-6-10",title:"Number Recognition 6-10",description:"Recognize, find, count, and trace numbers 6-10.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Recognition",keywords:["numbers 6-10","numerals","find","count","trace"],pdfPath:"worksheets/preschool/math/number-recognition/number-recognition-6-10.pdf",thumbnailPath:"thumbnails/preschool/math/number-recognition/number-recognition-6-10/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/number-recognition/number-recognition-6-10","thumbnails/preschool/math/number-recognition/number-recognition-6-10"),backHref:"number-recognition.html",backLabel:"Back to Number Recognition"},
  {id:"number-recognition-11-15",title:"Number Recognition 11-15",description:"Recognize, find, count, and trace numbers 11-15.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Recognition",keywords:["numbers 11-15","numerals","find","count","trace"],pdfPath:"worksheets/preschool/math/number-recognition/number-recognition-11-15.pdf",thumbnailPath:"thumbnails/preschool/math/number-recognition/number-recognition-11-15/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/number-recognition/number-recognition-11-15","thumbnails/preschool/math/number-recognition/number-recognition-11-15"),backHref:"number-recognition.html",backLabel:"Back to Number Recognition"},
  {id:"number-recognition-16-20",title:"Number Recognition 16-20",description:"Recognize, find, count, and trace numbers 16-20.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Recognition",keywords:["numbers 16-20","numerals","find","count","trace"],pdfPath:"worksheets/preschool/math/number-recognition/number-recognition-16-20.pdf",thumbnailPath:"thumbnails/preschool/math/number-recognition/number-recognition-16-20/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/number-recognition/number-recognition-16-20","thumbnails/preschool/math/number-recognition/number-recognition-16-20"),backHref:"number-recognition.html",backLabel:"Back to Number Recognition"},
  {id:"counting-objects-1-5",title:"Counting Objects 1-5",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Counting",keywords:["numbers 1-5","objects","quantities","count and circle","count and match","count and write","count and draw"],pdfPath:"worksheets/preschool/math/counting/counting-objects-1-5.pdf",thumbnailPath:"thumbnails/preschool/math/counting/counting-objects-1-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/counting/counting-objects-1-5","thumbnails/preschool/math/counting/counting-objects-1-5"),backHref:"skill-directory.html?skill=counting",backLabel:"Back to Counting"},
  {id:"counting-objects-1-10",title:"Counting Objects 1-10",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Counting",keywords:["numbers 1-10","objects","quantities","count and circle","count and match","count and write","count and draw"],pdfPath:"worksheets/preschool/math/counting/counting-objects-1-10.pdf",thumbnailPath:"thumbnails/preschool/math/counting/counting-objects-1-10/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/counting/counting-objects-1-10","thumbnails/preschool/math/counting/counting-objects-1-10"),backHref:"skill-directory.html?skill=counting",backLabel:"Back to Counting"},
  {id:"counting-objects-11-20",title:"Counting Objects 11-20",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Counting",keywords:["numbers 11-20","objects","quantities","count and circle","count and match","count and write","count and draw"],pdfPath:"worksheets/preschool/math/counting/counting-objects-11-20.pdf",thumbnailPath:"thumbnails/preschool/math/counting/counting-objects-11-20/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/counting/counting-objects-11-20","thumbnails/preschool/math/counting/counting-objects-11-20"),backHref:"skill-directory.html?skill=counting",backLabel:"Back to Counting"},
  {id:"number-order-1-10",title:"Number Order 1-10",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Order",keywords:["numbers 1-10","before","after","missing numbers","put in order","sequence"],pdfPath:"worksheets/preschool/math/number-order/number-order-1-10.pdf",thumbnailPath:"thumbnails/preschool/math/number-order/number-order-1-10/page-01.png",pageCount:4,pages:defineWorksheetPages(4,"worksheets/preschool/math/number-order/number-order-1-10","thumbnails/preschool/math/number-order/number-order-1-10"),backHref:"skill-directory.html?skill=number-order",backLabel:"Back to Number Order"},
  {id:"number-order-11-20",title:"Number Order 11-20",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Order",keywords:["numbers 11-20","before","after","missing numbers","put in order","sequence"],pdfPath:"worksheets/preschool/math/number-order/number-order-11-20.pdf",thumbnailPath:"thumbnails/preschool/math/number-order/number-order-11-20/page-01.png",pageCount:4,pages:defineWorksheetPages(4,"worksheets/preschool/math/number-order/number-order-11-20","thumbnails/preschool/math/number-order/number-order-11-20"),backHref:"skill-directory.html?skill=number-order",backLabel:"Back to Number Order"},
  {id:"more-fewer-same-1-10",title:"More, Fewer & Same 1-10",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"More, Fewer & Same",keywords:["numbers 1-10","compare groups","more","fewer","same","equal quantities"],pdfPath:"worksheets/preschool/math/more-fewer-same/more-fewer-same-1-10.pdf",thumbnailPath:"thumbnails/preschool/math/more-fewer-same/more-fewer-same-1-10/page-01.png",pageCount:4,pages:defineWorksheetPages(4,"worksheets/preschool/math/more-fewer-same/more-fewer-same-1-10","thumbnails/preschool/math/more-fewer-same/more-fewer-same-1-10"),backHref:"skill-directory.html?skill=more-fewer-same",backLabel:"Back to More, Fewer & Same"},
  {id:"addition-to-5",title:"Addition to 5",grade:"Preschool",subject:"Math",topic:"Early Addition & Subtraction",skill:"Addition",keywords:["sums to 5","pictures","put together","count and add","draw and add"],pdfPath:"worksheets/preschool/math/addition/addition-to-5.pdf",thumbnailPath:"thumbnails/preschool/math/addition/addition-to-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/addition/addition-to-5","thumbnails/preschool/math/addition/addition-to-5"),backHref:"skill-directory.html?skill=addition",backLabel:"Back to Early Addition & Subtraction"},
  {id:"subtracting-within-5",title:"Subtracting Within 5",grade:"Preschool",subject:"Math",topic:"Early Addition & Subtraction",skill:"Subtraction",keywords:["within 5","pictures","take away","cross out","draw and subtract"],pdfPath:"worksheets/preschool/math/subtraction/subtracting-within-5.pdf",thumbnailPath:"thumbnails/preschool/math/subtraction/subtracting-within-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/subtraction/subtracting-within-5","thumbnails/preschool/math/subtraction/subtracting-within-5"),backHref:"skill-directory.html?skill=addition",backLabel:"Back to Early Addition & Subtraction"},
  {id:"addition-facts-within-5",title:"Addition Facts Within 5",grade:"Preschool",subject:"Math",topic:"Early Addition & Subtraction",skill:"Addition Facts",keywords:["facts within 5","equations","horizontal addition","vertical addition","fill in answers"],pdfPath:"worksheets/preschool/math/addition/addition-facts-within-5.pdf",thumbnailPath:"thumbnails/preschool/math/addition/addition-facts-within-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/addition/addition-facts-within-5","thumbnails/preschool/math/addition/addition-facts-within-5"),backHref:"skill-directory.html?skill=addition",backLabel:"Back to Early Addition & Subtraction"},
  {id:"subtraction-facts-within-5",title:"Subtraction Facts Within 5",grade:"Preschool",subject:"Math",topic:"Early Addition & Subtraction",skill:"Subtraction Facts",keywords:["facts within 5","equations","horizontal subtraction","vertical subtraction","fill in answers"],pdfPath:"worksheets/preschool/math/subtraction/subtraction-facts-within-5.pdf",thumbnailPath:"thumbnails/preschool/math/subtraction/subtraction-facts-within-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/subtraction/subtraction-facts-within-5","thumbnails/preschool/math/subtraction/subtraction-facts-within-5"),backHref:"skill-directory.html?skill=addition",backLabel:"Back to Early Addition & Subtraction"},
  {id:"simple-addition-subtraction-stories",title:"Simple Addition & Subtraction Stories",description:"Use pictures and simple stories to add and take away within 5.",grade:"Preschool",subject:"Math",topic:"Early Addition & Subtraction",skill:"Math Stories",keywords:["story problems","math stories","addition within 5","subtraction within 5","put together","take away","draw the story"],pdfPath:"worksheets/preschool/math/addition/simple-addition-subtraction-stories.pdf",thumbnailPath:"thumbnails/preschool/math/addition/simple-addition-subtraction-stories/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/addition/simple-addition-subtraction-stories","thumbnails/preschool/math/addition/simple-addition-subtraction-stories"),backHref:"skill-directory.html?skill=addition",backLabel:"Back to Early Addition & Subtraction"},
  {id:"2d-shapes",title:"2D Shapes",description:"Recognize, find, match, trace, and draw basic 2D shapes.",grade:"Preschool",subject:"Math",topic:"Shapes & Spatial Skills",skill:"2D Shapes",keywords:["circle","square","triangle","rectangle","match shapes","trace shapes","shapes around us"],pdfPath:"worksheets/preschool/math/shapes/2d-shapes.pdf",thumbnailPath:"thumbnails/preschool/math/shapes/2d-shapes/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/shapes/2d-shapes","thumbnails/preschool/math/shapes/2d-shapes"),backHref:"topic.html?grade=Preschool&subject=Math&topic=Shapes%20%26%20Spatial%20Skills",backLabel:"Back to Shapes & Spatial Skills"},
  {id:"3d-shapes",title:"3D Shapes",description:"Recognize and match sphere, cube, cone, cylinder, and rectangular prism shapes.",grade:"Preschool",subject:"Math",topic:"Shapes & Spatial Skills",skill:"3D Shapes",keywords:["sphere","cube","cone","cylinder","rectangular prism","solid shapes","shapes around us"],pdfPath:"worksheets/preschool/math/shapes/3d-shapes.pdf",thumbnailPath:"thumbnails/preschool/math/shapes/3d-shapes/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/shapes/3d-shapes","thumbnails/preschool/math/shapes/3d-shapes"),backHref:"topic.html?grade=Preschool&subject=Math&topic=Shapes%20%26%20Spatial%20Skills",backLabel:"Back to Shapes & Spatial Skills"},
  {id:"positional-words",title:"Positional Words",description:"Learn and practice words that tell where objects are.",grade:"Preschool",subject:"Math",topic:"Shapes & Spatial Skills",skill:"Positional Words",keywords:["above","below","in","on","under","next to","between","spatial words"],pdfPath:"worksheets/preschool/math/shapes/positional-words.pdf",thumbnailPath:"thumbnails/preschool/math/shapes/positional-words/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/shapes/positional-words","thumbnails/preschool/math/shapes/positional-words"),backHref:"topic.html?grade=Preschool&subject=Math&topic=Shapes%20%26%20Spatial%20Skills",backLabel:"Back to Shapes & Spatial Skills"}
];
const requiredWorksheetResourceFields=["id","title","grade","subject","topic","skill","keywords","pdfPath","thumbnailPath","pageCount","pages"];
window.worksheetAssetBaseUrl="https://assets.simplelearningresources.com";
const worksheetAssetBaseUrl=window.worksheetAssetBaseUrl||"";
const resolveWorksheetAssetUrl=(path,baseUrl=worksheetAssetBaseUrl)=>{
  if(typeof path!=="string"||!path)throw new Error("Worksheet asset path is required.");
  if(typeof baseUrl!=="string")throw new Error("Worksheet asset base URL must be a string.");
  return baseUrl?`${baseUrl.replace(/\/+$/,"")}/${path.replace(/^\/+/,"")}`:path;
};
const validateWorksheetAssetResolver=()=>{
  const path="worksheets/example.pdf";
  if(resolveWorksheetAssetUrl(path,"")!==path)throw new Error("Local worksheet asset URL resolution failed.");
  if(resolveWorksheetAssetUrl(path,"https://assets.example.com/library/")!=="https://assets.example.com/library/worksheets/example.pdf")throw new Error("Remote worksheet asset URL resolution failed.");
};
const validateWorksheetResources=(resources)=>{
  const ids=new Set();
  const pagePreviewPaths=new Set();
  const pagePdfPaths=new Set();
  if(resources.length!==18)throw new Error(`Expected 18 canonical worksheet resources, found ${resources.length}.`);
  resources.forEach((resource)=>{
    const missing=requiredWorksheetResourceFields.filter((field)=>resource[field]===undefined||resource[field]===null||resource[field]==="");
    if(missing.length)throw new Error(`Worksheet resource ${resource.id||"(missing id)"} is missing: ${missing.join(", ")}`);
    if(ids.has(resource.id))throw new Error(`Duplicate worksheet resource id: ${resource.id}`);
    if(!Array.isArray(resource.keywords)||!resource.keywords.length)throw new Error(`Worksheet resource ${resource.id} requires keywords.`);
    if(!Number.isInteger(resource.pageCount)||resource.pageCount<1)throw new Error(`Worksheet resource ${resource.id} has an invalid pageCount.`);
    if(!Array.isArray(resource.pages)||resource.pages.length!==resource.pageCount)throw new Error(`Worksheet resource ${resource.id} pages must match pageCount.`);
    resource.pages.forEach((page,index)=>{
      const expectedNumber=index+1;
      if(page.number!==expectedNumber)throw new Error(`Worksheet resource ${resource.id} has non-sequential page numbering.`);
      if(typeof page.previewPath!=="string"||!page.previewPath.endsWith(`/page-${String(expectedNumber).padStart(2,"0")}.png`))throw new Error(`Worksheet resource ${resource.id} page ${expectedNumber} has an invalid previewPath.`);
      if(typeof page.pdfPath!=="string"||!page.pdfPath.endsWith(`/page-${String(expectedNumber).padStart(2,"0")}.pdf`))throw new Error(`Worksheet resource ${resource.id} page ${expectedNumber} has an invalid pdfPath.`);
      if(pagePreviewPaths.has(page.previewPath))throw new Error(`Duplicate worksheet page preview path: ${page.previewPath}`);
      if(pagePdfPaths.has(page.pdfPath))throw new Error(`Duplicate worksheet page PDF path: ${page.pdfPath}`);
      pagePreviewPaths.add(page.previewPath);
      pagePdfPaths.add(page.pdfPath);
    });
    if(resource.thumbnailPath!==resource.pages[0].previewPath)throw new Error(`Worksheet resource ${resource.id} thumbnailPath must equal its first page previewPath.`);
    ids.add(resource.id);
  });
};
validateWorksheetAssetResolver();
validateWorksheetResources(worksheetResourceDefinitions);
const worksheetResources=Object.freeze(worksheetResourceDefinitions.map((resource)=>Object.freeze({...resource,keywords:Object.freeze(resource.keywords),pages:Object.freeze(resource.pages.map((page)=>Object.freeze({...page,previewUrl:resolveWorksheetAssetUrl(page.previewPath),pdfUrl:resolveWorksheetAssetUrl(page.pdfPath)}))),pdfUrl:resolveWorksheetAssetUrl(resource.pdfPath),thumbnailUrl:resolveWorksheetAssetUrl(resource.thumbnailPath),previewHref:`resource-preview.html?resource=${encodeURIComponent(resource.id)}`,meta:`${resource.grade} • ${resource.subject} • ${resource.topic} • ${resource.skill}`.toUpperCase()})));
const worksheetResourcesById=Object.freeze(Object.fromEntries(worksheetResources.map((resource)=>[resource.id,resource])));
const normalizeResourceSearchValue=(value)=>String(value||"").trim().toLowerCase();
const searchWorksheetResources=({query="",grade="",subject="",topic="",skill=""}={})=>{
  const queryValue=normalizeResourceSearchValue(query);
  const filters={grade,subject,topic,skill};
  return worksheetResources.filter((resource)=>
    Object.entries(filters).every(([field,value])=>!value||normalizeResourceSearchValue(resource[field])===normalizeResourceSearchValue(value))&&
    (!queryValue||[resource.title,resource.grade,resource.subject,resource.topic,resource.skill,...resource.keywords].some((value)=>normalizeResourceSearchValue(value).includes(queryValue)))
  );
};
window.worksheetResources=worksheetResources;
window.worksheetResourcesById=worksheetResourcesById;
window.searchWorksheetResources=searchWorksheetResources;
window.resolveWorksheetAssetUrl=resolveWorksheetAssetUrl;

const renderDirectory = () => {
  const subjectNames={math:"Math",reading:"Reading & Language",communication:"Communication & Life Skills",science:"Science & Discovery",thinking:"Thinking & Our World"};
  const grades={preschool:"Preschool",kindergarten:"Kindergarten","grade-1":"Grade 1","grade-2":"Grade 2"};
  const numbersCountingSkills=[
    {title:"Number Recognition",description:"Recognize, find, count, and trace numbers.",href:"number-recognition.html"},
    {title:"Counting",description:"Count objects and connect groups to quantities.",href:"skill-directory.html?skill=counting"},
    {title:"Number Order",description:"Put numbers in order and find missing numbers.",href:"skill-directory.html?skill=number-order"},
    {title:"More, Fewer & Same",description:"Compare groups using visual quantities.",href:"skill-directory.html?skill=more-fewer-same"}
  ];
  const preschoolMathSkills=[
    ...numbersCountingSkills,
    {title:"Early Addition & Subtraction",description:"Put groups together and take groups apart.",href:"skill-directory.html?skill=addition"}
  ];
  const data={
    math:{preschool:"Numbers & Counting|Early Addition & Subtraction|Shapes & Spatial Skills|Patterns|Measurement & Comparing|Sorting & Data",kindergarten:"Numbers & Counting|Addition|Subtraction|Shapes & Geometry|Patterns|Measurement|Sorting & Data","grade-1":"Numbers & Place Value|Addition|Subtraction|Measurement|Time|Shapes & Fractions|Data & Graphing|Mathematical Thinking","grade-2":"Numbers & Place Value|Addition|Subtraction|Equal Groups & Arrays|Measurement|Time|Money|Data & Graphing|Geometry & Equal Shares"},
    reading:{preschool:"Alphabet|Print Awareness|Sound Awareness|Early Phonics|Vocabulary|Story & Comprehension|Early Writing",kindergarten:"Alphabet & Letter Formation|Phonological Awareness|Phonics|CVC Words|High-Frequency Words|Vocabulary|Sentences|Early Comprehension|Story Elements|Early Writing","grade-1":"Phonics & Word Reading|High-Frequency Words|Fluency|Vocabulary|Grammar & Sentences|Reading Comprehension|Story Elements|Informational Reading|Writing","grade-2":"Advanced Phonics|Fluency|Vocabulary|Grammar|Reading Comprehension|Literature|Informational Reading|Writing"},
    communication:{preschool:"Understanding Language|Expressing Needs & Ideas|WH Questions|Conversation & Play|Feelings & Social Understanding|Visual Supports & Routines|Independence & Safety",kindergarten:"Following Directions|WH Questions|Expressing Ideas|Conversation|Social Skills|Feelings & Regulation|Routines & Independence|Safety & Self-Advocacy","grade-1":"Following Directions|WH Questions|Describing & Explaining|Conversation|Social Communication|Emotions & Regulation|Independence|Self-Advocacy & Safety","grade-2":"Following Complex Directions|Asking & Answering Questions|Describing & Explaining|Conversation|Social Understanding|Emotional Problem Solving|Independence & Organization|Self-Advocacy & Safety"},
    science:{preschool:"Animals|Plants & Nature|Human Body & Five Senses|Weather & Seasons|Earth & Space|Living & Non-Living|Exploring Materials|Little Scientist",kindergarten:"Living Things|Plants|Animals|Human Body|Weather & Seasons|Earth & Sky|Materials & Motion|Scientific Thinking","grade-1":"Plants & Animals|Human Body & Health|Earth & Space|Weather|Materials & Motion|Scientific Thinking","grade-2":"Plants & Animals|Habitats & Life Cycles|Earth & Environment|Weather|Matter & Materials|Forces & Motion|Light & Sound|Scientific Thinking"},
    thinking:{preschool:"Logic & Matching|Myself & Family|Community|Maps & Places|Time & Sequence",kindergarten:"Logic & Problem Solving|Myself & Family|Community|Maps & Places|Past & Present|Needs & Wants","grade-1":"Logic & Reasoning|Families & Communities|Maps & Geography|Past & Present|Needs & Wants|Culture & Our World","grade-2":"Logic & Reasoning|Communities|Maps & Geography|Past & Present|Economics|People & Culture"}
  };
  const file=location.pathname.split("/").pop()||"index.html";
  const subjects={"math.html":"math","reading.html":"reading","communication.html":"communication","science.html":"science","thinking-world.html":"thinking"};
  const gradeFiles={"preschool.html":"preschool","kindergarten.html":"kindergarten","grade-1.html":"grade-1","grade-2.html":"grade-2"};
  const topicLink=(grade,subject,topic)=>grade==="preschool"&&subject==="math"&&topic==="Numbers & Counting"?"numbers-counting.html":grade==="preschool"&&subject==="math"&&topic==="Early Addition & Subtraction"?"skill-directory.html?skill=addition":"topic.html?grade="+encodeURIComponent(grades[grade])+"&subject="+encodeURIComponent(subjectNames[subject])+"&topic="+encodeURIComponent(topic);
  const block=(grade,subject)=>`<div class="directory-section"><h2>${grades[grade]}</h2><ul>${data[subject][grade].split("|").map(topic=>`<li><a href="${topicLink(grade,subject,topic)}">${topic}</a></li>`).join("")}</ul></div>`;
  const skillMarkup=(skills)=>`<div class="directory-grid skill-family-grid">${skills.map(skill=>`<div><h2><a href="${skill.href}">${skill.title}</a></h2><p>${skill.description}</p></div>`).join("")}</div>`;
  const library=document.querySelector("section.library");
  if(!library)return;
  if(subjects[file]){const subject=subjects[file];document.title=`${subjectNames[subject]} | Learning Made Simple`;library.innerHTML=subject==="math"?`<div class="library-header"><p class="eyebrow">PRESCHOOL MATH</p><h1>Math Worksheets</h1><p>Browse current preschool math skills.</p></div>${skillMarkup(preschoolMathSkills)}`:`<div class="library-header"><p class="eyebrow">RESOURCE DIRECTORY</p><h1>${subjectNames[subject]}</h1><p>Browse topics by grade.</p></div><div class="directory-grid subject-directory">${Object.keys(grades).map(grade=>block(grade,subject)).join("")}</div>`;}
  if(gradeFiles[file]){const grade=gradeFiles[file];document.title=`${grades[grade]} | Learning Made Simple`;library.innerHTML=`<div class="library-header"><p class="eyebrow">GRADE DIRECTORY</p><h1>${grades[grade]}</h1><p>Browse resources by subject.</p></div><div class="directory-grid grade-directory">${Object.keys(subjectNames).map(subject=>`<div class="directory-section" id="${subject}"><h2>${subjectNames[subject]}</h2><ul>${data[subject][grade].split("|").map(topic=>`<li><a href="${topicLink(grade,subject,topic)}">${topic}</a></li>`).join("")}</ul></div>`).join("")}</div>`;}
  if(file==="numbers-counting.html"){document.title="Numbers & Counting | Learning Made Simple";library.innerHTML=`<div class="library-header"><p class="eyebrow">PRESCHOOL &bull; MATH</p><h1>Numbers &amp; Counting</h1><p>Choose a number skill family.</p></div>${skillMarkup(numbersCountingSkills)}`;}
};
if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", renderDirectory); else renderDirectory();
