const renderDirectory = () => {
  const subjectNames={math:"Math",reading:"Reading & Language",communication:"Communication & Life Skills",science:"Science & Discovery",thinking:"Thinking & Our World"};
  const grades={preschool:"Preschool",kindergarten:"Kindergarten","grade-1":"Grade 1","grade-2":"Grade 2"};
  const data={
    math:{preschool:"Numbers & Counting|Early Addition & Subtraction|Shapes & Spatial Skills|Patterns|Measurement & Comparing|Sorting & Data",kindergarten:"Numbers & Counting|Addition|Subtraction|Shapes & Geometry|Patterns|Measurement|Sorting & Data","grade-1":"Numbers & Place Value|Addition|Subtraction|Measurement|Time|Shapes & Fractions|Data & Graphing|Mathematical Thinking","grade-2":"Numbers & Place Value|Addition|Subtraction|Equal Groups & Arrays|Measurement|Time|Money|Data & Graphing|Geometry & Equal Shares"},
    reading:{preschool:"Alphabet|Print Awareness|Sound Awareness|Early Phonics|Vocabulary|Story & Comprehension|Early Writing",kindergarten:"Alphabet & Letter Formation|Phonological Awareness|Phonics|CVC Words|High-Frequency Words|Vocabulary|Sentences|Early Comprehension|Story Elements|Early Writing","grade-1":"Phonics & Word Reading|High-Frequency Words|Fluency|Vocabulary|Grammar & Sentences|Reading Comprehension|Story Elements|Informational Reading|Writing","grade-2":"Advanced Phonics|Fluency|Vocabulary|Grammar|Reading Comprehension|Literature|Informational Reading|Writing"},
    communication:{preschool:"Understanding Language|Expressing Needs & Ideas|WH Questions|Conversation & Play|Feelings & Social Understanding|Visual Supports & Routines|Independence & Safety",kindergarten:"Following Directions|WH Questions|Expressing Ideas|Conversation|Social Skills|Feelings & Regulation|Routines & Independence|Safety & Self-Advocacy","grade-1":"Following Directions|WH Questions|Describing & Explaining|Conversation|Social Communication|Emotions & Regulation|Independence|Self-Advocacy & Safety","grade-2":"Following Complex Directions|Asking & Answering Questions|Describing & Explaining|Conversation|Social Understanding|Emotional Problem Solving|Independence & Organization|Self-Advocacy & Safety"},
    science:{preschool:"Animals|Plants & Nature|Human Body & Five Senses|Weather & Seasons|Earth & Space|Living & Non-Living|Exploring Materials|Little Scientist",kindergarten:"Living Things|Plants|Animals|Human Body|Weather & Seasons|Earth & Sky|Materials & Motion|Scientific Thinking","grade-1":"Plants & Animals|Human Body & Health|Earth & Space|Weather|Materials & Motion|Scientific Thinking","grade-2":"Plants & Animals|Habitats & Life Cycles|Earth & Environment|Weather|Matter & Materials|Forces & Motion|Light & Sound|Scientific Thinking"},
    thinking:{preschool:"Logic & Matching|Myself & Family|Community|Maps & Places|Time & Sequence",kindergarten:"Logic & Problem Solving|Myself & Family|Community|Maps & Places|Past & Present|Needs & Wants","grade-1":"Logic & Reasoning|Families & Communities|Maps & Geography|Past & Present|Needs & Wants|Culture & Our World","grade-2":"Logic & Reasoning|Communities|Maps & Geography|Past & Present|Economics|People & Culture"}
  };
  const file=location.pathname.split("/").pop()||"index.html";
  const subjects={"math.html":"math","reading.html":"reading","communication.html":"communication","science.html":"science","thinking-world.html":"thinking"};
  const gradeFiles={"preschool.html":"preschool","kindergarten.html":"kindergarten","grade-1.html":"grade-1","grade-2.html":"grade-2"};
  const topicLink=(grade,subject,topic)=>grade==="preschool"&&subject==="math"&&topic==="Numbers & Counting"?"number-recognition.html":"topic.html?grade="+encodeURIComponent(grades[grade])+"&subject="+encodeURIComponent(subjectNames[subject])+"&topic="+encodeURIComponent(topic);
  const block=(grade,subject)=>`<div class="directory-section"><h2>${grades[grade]}</h2><ul>${data[subject][grade].split("|").map(topic=>`<li><a href="${topicLink(grade,subject,topic)}">${topic}</a></li>`).join("")}</ul></div>`;
  const library=document.querySelector("section.library");
  if(!library)return;
  if(subjects[file]){const subject=subjects[file];document.title=`${subjectNames[subject]} | Learning Made Simple`;library.innerHTML=`<div class="library-header"><p class="eyebrow">RESOURCE DIRECTORY</p><h1>${subjectNames[subject]}</h1><p>Browse topics by grade.</p></div><div class="directory-grid subject-directory">${Object.keys(grades).map(grade=>block(grade,subject)).join("")}</div>`;}
  if(gradeFiles[file]){const grade=gradeFiles[file];document.title=`${grades[grade]} | Learning Made Simple`;library.innerHTML=`<div class="library-header"><p class="eyebrow">GRADE DIRECTORY</p><h1>${grades[grade]}</h1><p>Browse resources by subject.</p></div><div class="directory-grid grade-directory">${Object.keys(subjectNames).map(subject=>`<div class="directory-section" id="${subject}"><h2>${subjectNames[subject]}</h2><ul>${data[subject][grade].split("|").map(topic=>`<li><a href="${topicLink(grade,subject,topic)}">${topic}</a></li>`).join("")}</ul></div>`).join("")}</div>`;}
};
if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", renderDirectory); else renderDirectory();
