const defineWorksheetPages=(pageCount,pdfDirectory,previewDirectory)=>Array.from({length:pageCount},(_,index)=>{
  const number=index+1;
  const filename=`page-${String(number).padStart(2,"0")}`;
  return {number,previewPath:`${previewDirectory}/${filename}.png`,pdfPath:`${pdfDirectory}/${filename}.pdf`};
});
const worksheetResourceDefinitions = [
  {id:"follow-directions",title:"Follow the Directions",description:"Listen for clues, explore position words, and follow one-step and two-step directions.",grade:"Preschool",subject:"Communication & Life Skills",topic:"Understanding Language",skill:"Following Directions",keywords:["following directions","listening","one-step directions","two-step directions","position words","listen for the clue"],pdfPath:"worksheets/preschool/communication/follow-directions/follow-directions.pdf",thumbnailPath:"thumbnails/preschool/communication/follow-directions/follow-directions/page-01.png",pageCount:4,pageLabels:["One-Step Directions","Listen for the Clue","Where Is It?","Two-Step Directions"],pages:defineWorksheetPages(4,"worksheets/preschool/communication/follow-directions/follow-directions","thumbnails/preschool/communication/follow-directions/follow-directions"),backHref:"topic.html?grade=Preschool&subject=Communication%20%26%20Life%20Skills&topic=Understanding%20Language",backLabel:"Back to Understanding Language"},
  {id:"i-can-tell-you",title:"I Can Tell You",description:"Practice simple phrases for expressing needs, wants, choices, and boundaries.",grade:"Preschool",subject:"Communication & Life Skills",topic:"Expressing Needs & Ideas",skill:"Expressing Needs & Ideas",keywords:["expressing needs","expressing wants","functional communication","self-advocacy","making choices","saying no"],pdfPath:"worksheets/preschool/communication/i-can-tell-you/i-can-tell-you.pdf",thumbnailPath:"thumbnails/preschool/communication/i-can-tell-you/i-can-tell-you/page-01.png",pageCount:4,pageLabels:["What Do You Need?","What Can I Say?","Tell What You Want","I Can Say No"],pages:defineWorksheetPages(4,"worksheets/preschool/communication/i-can-tell-you/i-can-tell-you","thumbnails/preschool/communication/i-can-tell-you/i-can-tell-you"),backHref:"topic.html?grade=Preschool&subject=Communication%20%26%20Life%20Skills&topic=Expressing%20Needs%20%26%20Ideas",backLabel:"Back to Expressing Needs & Ideas"},
  {id:"i-can-ask-for-help",title:"I Can Ask for Help",description:"Practice recognizing when help is needed and asking trusted adults for help.",grade:"Preschool",subject:"Communication & Life Skills",topic:"Expressing Needs & Ideas",skill:"Asking for Help",keywords:["asking for help","expressing needs","functional communication","trusted adults","self-advocacy"],pdfPath:"worksheets/preschool/communication/i-can-ask-for-help/i-can-ask-for-help.pdf",thumbnailPath:"thumbnails/preschool/communication/i-can-ask-for-help/i-can-ask-for-help/page-01.png",pageCount:4,pageLabels:["When Do I Need Help?","I Can Ask for Help","Who Can Help Me?","Now I Can Say It"],pages:defineWorksheetPages(4,"worksheets/preschool/communication/i-can-ask-for-help/i-can-ask-for-help","thumbnails/preschool/communication/i-can-ask-for-help/i-can-ask-for-help"),backHref:"topic.html?grade=Preschool&subject=Communication%20%26%20Life%20Skills&topic=Expressing%20Needs%20%26%20Ideas",backLabel:"Back to Expressing Needs & Ideas"},
  {id:"feelings-me",title:"Feelings & Me",description:"Recognize and name feelings, explore how others feel, and share your own feelings.",grade:"Preschool",subject:"Communication & Life Skills",topic:"Feelings & Social Understanding",skill:"Feelings",keywords:["feelings","emotions","social understanding","find the feeling","name the feeling","feelings happen","how do you feel","self-expression"],pdfPath:"worksheets/preschool/communication/feelings/feelings-me.pdf",thumbnailPath:"thumbnails/preschool/communication/feelings/feelings-me/page-01.png",pageCount:4,pageLabels:["Find the Feeling","Name the Feeling","Feelings Happen","How Do You Feel?"],pages:defineWorksheetPages(4,"worksheets/preschool/communication/feelings/feelings-me","thumbnails/preschool/communication/feelings/feelings-me"),backHref:"topic.html?grade=Preschool&subject=Communication%20%26%20Life%20Skills&topic=Feelings%20%26%20Social%20Understanding",backLabel:"Back to Feelings & Social Understanding"},
  // Keep Preschool Reading resources in learning progression; add new entries after their prerequisites.
  {id:"learn-my-letters-a-z",pageLabels:Array.from({length:26},(_,index)=>`Letter ${String.fromCharCode(65+index)}`),title:"Learn My Letters A-Z",description:"Explore uppercase and lowercase letters with pictures and letter hunts.",grade:"Preschool",subject:"Reading & Language",topic:"Alphabet",skill:"Letter Recognition",keywords:["alphabet","letters","A-Z","uppercase","lowercase","letter recognition","letter hunt"],pdfPath:"worksheets/preschool/reading/letters/learn-my-letters-a-z.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/learn-my-letters-a-z/page-01.png",pageCount:26,pages:defineWorksheetPages(26,"worksheets/preschool/reading/letters/learn-my-letters-a-z","thumbnails/preschool/reading/letters/learn-my-letters-a-z"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Alphabet",backLabel:"Back to Alphabet"},
  {id:"trace-my-letters-a-z",pageLabels:Array.from({length:26},(_,index)=>`Letter ${String.fromCharCode(65+index)}`),title:"Trace My Letters A-Z",description:"Practice tracing uppercase and lowercase letters from A to Z.",grade:"Preschool",subject:"Reading & Language",topic:"Alphabet",skill:"Letter Tracing",keywords:["alphabet","letters","A-Z","uppercase","lowercase","letter tracing","handwriting","letter formation"],pdfPath:"worksheets/preschool/reading/letters/trace-my-letters-a-z.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/trace-my-letters-a-z/page-01.png",pageCount:26,pages:defineWorksheetPages(26,"worksheets/preschool/reading/letters/trace-my-letters-a-z","thumbnails/preschool/reading/letters/trace-my-letters-a-z"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Alphabet",backLabel:"Back to Alphabet"},
  {id:"match-big-little-letters-a-z",title:"Match Big & Little Letters A-Z",description:"Match uppercase and lowercase letters from A to Z.",grade:"Preschool",subject:"Reading & Language",topic:"Alphabet",skill:"Letter Matching",keywords:["alphabet","letters","A-Z","uppercase","lowercase","big letters","little letters","letter matching"],pdfPath:"worksheets/preschool/reading/letters/match-big-little-letters-a-z.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/match-big-little-letters-a-z/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/reading/letters/match-big-little-letters-a-z","thumbnails/preschool/reading/letters/match-big-little-letters-a-z"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Alphabet",backLabel:"Back to Alphabet"},
  {id:"abc-order-missing-letters",title:"ABC Order & Missing Letters",description:"Practice alphabet order and fill in missing letters.",grade:"Preschool",subject:"Reading & Language",topic:"Alphabet",skill:"Alphabet Order",keywords:["alphabet","letters","ABC order","alphabet order","missing letters","letter sequence"],pdfPath:"worksheets/preschool/reading/letters/abc-order-missing-letters.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/abc-order-missing-letters/page-01.png",pageCount:2,pages:defineWorksheetPages(2,"worksheets/preschool/reading/letters/abc-order-missing-letters","thumbnails/preschool/reading/letters/abc-order-missing-letters"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Alphabet",backLabel:"Back to Alphabet"},
  {id:"parts-of-a-book",title:"Parts of a Book",description:"Explore book parts and practice early print awareness.",grade:"Preschool",subject:"Reading & Language",topic:"Print Awareness",skill:"Parts of a Book",keywords:["book parts","parts of a book","print awareness","front cover","back cover","title","author","reading direction","left to right"],pdfPath:"worksheets/preschool/reading/letters/parts-of-a-book.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/parts-of-a-book/page-01.png",pageCount:4,pages:defineWorksheetPages(4,"worksheets/preschool/reading/letters/parts-of-a-book","thumbnails/preschool/reading/letters/parts-of-a-book"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Print%20Awareness",backLabel:"Back to Print Awareness"},
  {id:"beginning-sounds",title:"Beginning Sounds",description:"Listen for beginning sounds and match pictures to letters.",grade:"Preschool",subject:"Reading & Language",topic:"Sounds & Beginning Phonics",skill:"Beginning Sounds",keywords:["beginning sounds","initial sounds","letter sounds","phonics","sound awareness","early phonics"],pdfPath:"worksheets/preschool/reading/letters/beginning-sounds.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/beginning-sounds/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/reading/letters/beginning-sounds","thumbnails/preschool/reading/letters/beginning-sounds"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Sounds%20%26%20Beginning%20Phonics",backLabel:"Back to Sounds & Beginning Phonics"},
  {id:"rhyming-pictures",title:"Rhyming Pictures",description:"Match pictures and find words that rhyme.",grade:"Preschool",subject:"Reading & Language",topic:"Rhymes & Word Beats",skill:"Rhyming",keywords:["rhymes","rhyming","rhyming pictures","word sounds","phonological awareness","word beats"],pdfPath:"worksheets/preschool/reading/letters/rhyming-pictures.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/rhyming-pictures/page-01.png",pageCount:2,pages:defineWorksheetPages(2,"worksheets/preschool/reading/letters/rhyming-pictures","thumbnails/preschool/reading/letters/rhyming-pictures"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Rhymes%20%26%20Word%20Beats",backLabel:"Back to Rhymes & Word Beats"},
  {id:"clap-the-syllables",title:"Clap the Syllables",description:"Clap and count word beats with colorful pictures.",grade:"Preschool",subject:"Reading & Language",topic:"Rhymes & Word Beats",skill:"Syllables",keywords:["syllables","clap","word beats","phonological awareness","count syllables"],pdfPath:"worksheets/preschool/reading/letters/clap-the-syllables.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/clap-the-syllables/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/reading/letters/clap-the-syllables","thumbnails/preschool/reading/letters/clap-the-syllables"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Rhymes%20%26%20Word%20Beats",backLabel:"Back to Rhymes & Word Beats"},
  {id:"opposites",title:"Opposites",description:"Explore opposite words with colorful pictures and simple activities.",grade:"Preschool",subject:"Reading & Language",topic:"Words & Vocabulary",skill:"Opposites",keywords:["opposites","opposite words","vocabulary","big and small","full and empty","open and closed"],pdfPath:"worksheets/preschool/reading/letters/opposites.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/opposites/page-01.png",pageCount:4,pages:defineWorksheetPages(4,"worksheets/preschool/reading/letters/opposites","thumbnails/preschool/reading/letters/opposites"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Words%20%26%20Vocabulary",backLabel:"Back to Words & Vocabulary"},
  {id:"categories",title:"Categories",description:"Explore groups of familiar things and what we use them for.",grade:"Preschool",subject:"Reading & Language",topic:"Words & Vocabulary",skill:"Categories",keywords:["categories","categorizing","groups","sorting","vocabulary","what we use","everyday objects"],pdfPath:"worksheets/preschool/reading/letters/categories.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/categories/page-01.png",pageCount:4,pages:defineWorksheetPages(4,"worksheets/preschool/reading/letters/categories","thumbnails/preschool/reading/letters/categories"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Words%20%26%20Vocabulary",backLabel:"Back to Words & Vocabulary"},
  {id:"story-comprehension",title:"Story & Comprehension",description:"Explore picture stories, put events in order, and tell what happens next.",grade:"Preschool",subject:"Reading & Language",topic:"Story & Comprehension",skill:"Story Comprehension",keywords:["stories","story comprehension","look and answer","picture sequencing","what happens next","draw what happens next","beginning middle end"],pdfPath:"worksheets/preschool/reading/letters/story-comprehension.pdf",thumbnailPath:"thumbnails/preschool/reading/letters/story-comprehension/page-01.png",pageCount:5,pageLabels:["Look and Answer","Picture Sequencing","What Happens Next?","Draw What Happens Next","Beginning, Middle & End"],pages:defineWorksheetPages(5,"worksheets/preschool/reading/letters/story-comprehension","thumbnails/preschool/reading/letters/story-comprehension"),backHref:"topic.html?grade=Preschool&subject=Reading%20%26%20Language&topic=Story%20%26%20Comprehension",backLabel:"Back to Story & Comprehension"},
  {"id":"trace-numbers-1-20","title":"Trace Numbers 1-20","description":"Trace all twenty numbers in a spacious grid.","grade":"Preschool","subject":"Math","topic":"Numbers & Counting","skill":"Number Tracing","keywords":["trace","numbers 1-20","number formation","handwriting"],"pdfPath":"worksheets/preschool/math/numbers-counting/trace-numbers-1-20.pdf","thumbnailPath":"thumbnails/preschool/math/numbers-counting/trace-numbers-1-20/page-01.png","pageCount":1,"pages":[{"number":1,"previewPath":"thumbnails/preschool/math/numbers-counting/trace-numbers-1-20/page-01.png","pdfPath":"worksheets/preschool/math/numbers-counting/trace-numbers-1-20/page-01.pdf"}],"backHref":"numbers-counting.html","backLabel":"Back to Numbers & Counting"},
  {"id":"missing-numbers-1-20","title":"Missing Numbers 1-20","description":"Count along each row and write the missing numbers.","grade":"Preschool","subject":"Math","topic":"Numbers & Counting","skill":"Number Order","keywords":["missing numbers","numbers 1-20","sequence","number order"],"pdfPath":"worksheets/preschool/math/numbers-counting/missing-numbers-1-20.pdf","thumbnailPath":"thumbnails/preschool/math/numbers-counting/missing-numbers-1-20/page-01.png","pageCount":1,"pages":[{"number":1,"previewPath":"thumbnails/preschool/math/numbers-counting/missing-numbers-1-20/page-01.png","pdfPath":"worksheets/preschool/math/numbers-counting/missing-numbers-1-20/page-01.pdf"}],"backHref":"numbers-counting.html","backLabel":"Back to Numbers & Counting"},
  {"id":"connect-the-dots-1-20","title":"Connect the Dots 1-20","description":"Connect numbers 1-20 to finish a cheerful rocket.","grade":"Preschool","subject":"Math","topic":"Numbers & Counting","skill":"Counting","keywords":["connect the dots","numbers 1-20","rocket","space","counting"],"pdfPath":"worksheets/preschool/math/numbers-counting/connect-the-dots-1-20.pdf","thumbnailPath":"thumbnails/preschool/math/numbers-counting/connect-the-dots-1-20/page-01.png","pageCount":1,"pages":[{"number":1,"previewPath":"thumbnails/preschool/math/numbers-counting/connect-the-dots-1-20/page-01.png","pdfPath":"worksheets/preschool/math/numbers-counting/connect-the-dots-1-20/page-01.pdf"}],"backHref":"numbers-counting.html","backLabel":"Back to Numbers & Counting"},
  {id:"number-recognition-1-5",title:"Number Recognition 1-5",description:"Recognize, find, count, and trace numbers 1-5.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Recognition",keywords:["numbers 1-5","numerals","find","count","trace"],pdfPath:"worksheets/preschool/math/number-recognition/number-recognition-1-5.pdf",thumbnailPath:"thumbnails/preschool/math/number-recognition/number-recognition-1-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/number-recognition/number-recognition-1-5","thumbnails/preschool/math/number-recognition/number-recognition-1-5"),backHref:"number-recognition.html",backLabel:"Back to Number Recognition"},
  {id:"number-recognition-6-10",title:"Number Recognition 6-10",description:"Recognize, find, count, and trace numbers 6-10.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Recognition",keywords:["numbers 6-10","numerals","find","count","trace"],pdfPath:"worksheets/preschool/math/number-recognition/number-recognition-6-10.pdf",thumbnailPath:"thumbnails/preschool/math/number-recognition/number-recognition-6-10/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/number-recognition/number-recognition-6-10","thumbnails/preschool/math/number-recognition/number-recognition-6-10"),backHref:"number-recognition.html",backLabel:"Back to Number Recognition"},
  {id:"number-recognition-11-15",title:"Number Recognition 11-15",description:"Recognize, find, count, and trace numbers 11-15.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Recognition",keywords:["numbers 11-15","numerals","find","count","trace"],pdfPath:"worksheets/preschool/math/number-recognition/number-recognition-11-15.pdf",thumbnailPath:"thumbnails/preschool/math/number-recognition/number-recognition-11-15/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/number-recognition/number-recognition-11-15","thumbnails/preschool/math/number-recognition/number-recognition-11-15"),backHref:"number-recognition.html",backLabel:"Back to Number Recognition"},
  {id:"number-recognition-16-20",title:"Number Recognition 16-20",description:"Recognize, find, count, and trace numbers 16-20.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Recognition",keywords:["numbers 16-20","numerals","find","count","trace"],pdfPath:"worksheets/preschool/math/number-recognition/number-recognition-16-20.pdf",thumbnailPath:"thumbnails/preschool/math/number-recognition/number-recognition-16-20/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/number-recognition/number-recognition-16-20","thumbnails/preschool/math/number-recognition/number-recognition-16-20"),backHref:"number-recognition.html",backLabel:"Back to Number Recognition"},
  {id:"counting-objects-1-5",title:"Counting Objects 1-5",description:"Count groups of objects from 1 to 5.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Counting",keywords:["numbers 1-5","objects","quantities","count and circle","count and match","count and write","count and draw"],pdfPath:"worksheets/preschool/math/counting/counting-objects-1-5.pdf",thumbnailPath:"thumbnails/preschool/math/counting/counting-objects-1-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/counting/counting-objects-1-5","thumbnails/preschool/math/counting/counting-objects-1-5"),backHref:"skill-directory.html?skill=counting",backLabel:"Back to Counting"},
  {id:"counting-objects-1-10",title:"Counting Objects 1-10",description:"Count groups of objects from 1 to 10.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Counting",keywords:["numbers 1-10","objects","quantities","count and circle","count and match","count and write","count and draw"],pdfPath:"worksheets/preschool/math/counting/counting-objects-1-10.pdf",thumbnailPath:"thumbnails/preschool/math/counting/counting-objects-1-10/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/counting/counting-objects-1-10","thumbnails/preschool/math/counting/counting-objects-1-10"),backHref:"skill-directory.html?skill=counting",backLabel:"Back to Counting"},
  {id:"counting-objects-11-20",title:"Counting Objects 11-20",description:"Count groups of objects from 11 to 20.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Counting",keywords:["numbers 11-20","objects","quantities","count and circle","count and match","count and write","count and draw"],pdfPath:"worksheets/preschool/math/counting/counting-objects-11-20.pdf",thumbnailPath:"thumbnails/preschool/math/counting/counting-objects-11-20/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/counting/counting-objects-11-20","thumbnails/preschool/math/counting/counting-objects-11-20"),backHref:"skill-directory.html?skill=counting",backLabel:"Back to Counting"},
  {id:"number-order-1-10",title:"Number Order 1-10",description:"Practice number order and missing numbers from 1 to 10.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Order",keywords:["numbers 1-10","before","after","missing numbers","put in order","sequence"],pdfPath:"worksheets/preschool/math/number-order/number-order-1-10.pdf",thumbnailPath:"thumbnails/preschool/math/number-order/number-order-1-10/page-01.png",pageCount:4,pages:defineWorksheetPages(4,"worksheets/preschool/math/number-order/number-order-1-10","thumbnails/preschool/math/number-order/number-order-1-10"),backHref:"skill-directory.html?skill=number-order",backLabel:"Back to Number Order"},
  {id:"number-order-11-20",title:"Number Order 11-20",description:"Practice number order and missing numbers from 11 to 20.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"Number Order",keywords:["numbers 11-20","before","after","missing numbers","put in order","sequence"],pdfPath:"worksheets/preschool/math/number-order/number-order-11-20.pdf",thumbnailPath:"thumbnails/preschool/math/number-order/number-order-11-20/page-01.png",pageCount:4,pages:defineWorksheetPages(4,"worksheets/preschool/math/number-order/number-order-11-20","thumbnails/preschool/math/number-order/number-order-11-20"),backHref:"skill-directory.html?skill=number-order",backLabel:"Back to Number Order"},
  {id:"more-fewer-same-1-10",title:"More, Fewer & Same 1-10",description:"Compare groups within 10 as more, fewer, or the same.",grade:"Preschool",subject:"Math",topic:"Numbers & Counting",skill:"More, Fewer & Same",keywords:["numbers 1-10","compare groups","more","fewer","same","equal quantities"],pdfPath:"worksheets/preschool/math/more-fewer-same/more-fewer-same-1-10.pdf",thumbnailPath:"thumbnails/preschool/math/more-fewer-same/more-fewer-same-1-10/page-01.png",pageCount:4,pages:defineWorksheetPages(4,"worksheets/preschool/math/more-fewer-same/more-fewer-same-1-10","thumbnails/preschool/math/more-fewer-same/more-fewer-same-1-10"),backHref:"skill-directory.html?skill=more-fewer-same",backLabel:"Back to More, Fewer & Same"},
  {id:"addition-to-5",title:"Addition to 5",description:"Add picture groups with totals up to 5.",grade:"Preschool",subject:"Math",topic:"Early Addition & Subtraction",skill:"Addition",keywords:["sums to 5","pictures","put together","count and add","draw and add"],pdfPath:"worksheets/preschool/math/addition/addition-to-5.pdf",thumbnailPath:"thumbnails/preschool/math/addition/addition-to-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/addition/addition-to-5","thumbnails/preschool/math/addition/addition-to-5"),backHref:"skill-directory.html?skill=addition",backLabel:"Back to Early Addition & Subtraction"},
  {id:"subtracting-within-5",title:"Subtracting Within 5",description:"Take away pictured objects within 5.",grade:"Preschool",subject:"Math",topic:"Early Addition & Subtraction",skill:"Subtraction",keywords:["within 5","pictures","take away","cross out","draw and subtract"],pdfPath:"worksheets/preschool/math/subtraction/subtracting-within-5.pdf",thumbnailPath:"thumbnails/preschool/math/subtraction/subtracting-within-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/subtraction/subtracting-within-5","thumbnails/preschool/math/subtraction/subtracting-within-5"),backHref:"skill-directory.html?skill=addition",backLabel:"Back to Early Addition & Subtraction"},
  {id:"addition-facts-within-5",title:"Addition Facts Within 5",description:"Solve horizontal and vertical addition facts within 5.",grade:"Preschool",subject:"Math",topic:"Early Addition & Subtraction",skill:"Addition Facts",keywords:["facts within 5","equations","horizontal addition","vertical addition","fill in answers"],pdfPath:"worksheets/preschool/math/addition/addition-facts-within-5.pdf",thumbnailPath:"thumbnails/preschool/math/addition/addition-facts-within-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/addition/addition-facts-within-5","thumbnails/preschool/math/addition/addition-facts-within-5"),backHref:"skill-directory.html?skill=addition",backLabel:"Back to Early Addition & Subtraction"},
  {id:"subtraction-facts-within-5",title:"Subtraction Facts Within 5",description:"Solve horizontal and vertical subtraction facts within 5.",grade:"Preschool",subject:"Math",topic:"Early Addition & Subtraction",skill:"Subtraction Facts",keywords:["facts within 5","equations","horizontal subtraction","vertical subtraction","fill in answers"],pdfPath:"worksheets/preschool/math/subtraction/subtraction-facts-within-5.pdf",thumbnailPath:"thumbnails/preschool/math/subtraction/subtraction-facts-within-5/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/subtraction/subtraction-facts-within-5","thumbnails/preschool/math/subtraction/subtraction-facts-within-5"),backHref:"skill-directory.html?skill=addition",backLabel:"Back to Early Addition & Subtraction"},
  {id:"simple-addition-subtraction-stories",title:"Simple Addition & Subtraction Stories",description:"Use pictures and simple stories to add and take away within 5.",grade:"Preschool",subject:"Math",topic:"Early Addition & Subtraction",skill:"Math Stories",keywords:["story problems","math stories","addition within 5","subtraction within 5","put together","take away","draw the story"],pdfPath:"worksheets/preschool/math/addition/simple-addition-subtraction-stories.pdf",thumbnailPath:"thumbnails/preschool/math/addition/simple-addition-subtraction-stories/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/addition/simple-addition-subtraction-stories","thumbnails/preschool/math/addition/simple-addition-subtraction-stories"),backHref:"skill-directory.html?skill=addition",backLabel:"Back to Early Addition & Subtraction"},
  {id:"2d-shapes",title:"2D Shapes",description:"Recognize, find, match, trace, and draw basic 2D shapes.",grade:"Preschool",subject:"Math",topic:"Shapes & Spatial Skills",skill:"2D Shapes",keywords:["circle","square","triangle","rectangle","match shapes","trace shapes","shapes around us"],pdfPath:"worksheets/preschool/math/shapes/2d-shapes.pdf",thumbnailPath:"thumbnails/preschool/math/shapes/2d-shapes/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/shapes/2d-shapes","thumbnails/preschool/math/shapes/2d-shapes"),backHref:"topic.html?grade=Preschool&subject=Math&topic=Shapes%20%26%20Spatial%20Skills",backLabel:"Back to Shapes & Spatial Skills"},
  {id:"3d-shapes",title:"3D Shapes",description:"Recognize and match sphere, cube, cone, cylinder, and rectangular prism shapes.",grade:"Preschool",subject:"Math",topic:"Shapes & Spatial Skills",skill:"3D Shapes",keywords:["sphere","cube","cone","cylinder","rectangular prism","solid shapes","shapes around us"],pdfPath:"worksheets/preschool/math/shapes/3d-shapes.pdf",thumbnailPath:"thumbnails/preschool/math/shapes/3d-shapes/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/shapes/3d-shapes","thumbnails/preschool/math/shapes/3d-shapes"),backHref:"topic.html?grade=Preschool&subject=Math&topic=Shapes%20%26%20Spatial%20Skills",backLabel:"Back to Shapes & Spatial Skills"},
  {id:"positional-words",title:"Positional Words",description:"Learn and practice words that tell where objects are.",grade:"Preschool",subject:"Math",topic:"Shapes & Spatial Skills",skill:"Positional Words",keywords:["above","below","in","on","under","next to","between","spatial words"],pdfPath:"worksheets/preschool/math/shapes/positional-words.pdf",thumbnailPath:"thumbnails/preschool/math/shapes/positional-words/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/shapes/positional-words","thumbnails/preschool/math/shapes/positional-words"),backHref:"topic.html?grade=Preschool&subject=Math&topic=Shapes%20%26%20Spatial%20Skills",backLabel:"Back to Shapes & Spatial Skills"},
  {id:"preschool-patterns",title:"Preschool Patterns",description:"Meet repeating patterns, find what comes next, and create simple shape patterns.",grade:"Preschool",subject:"Math",topic:"Patterns",skill:"Patterns",keywords:["patterns","repeating patterns","what comes next","finish the pattern","copy the pattern","create a pattern"],pdfPath:"worksheets/preschool/math/patterns/preschool-patterns.pdf",thumbnailPath:"thumbnails/preschool/math/patterns/preschool-patterns/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/patterns/preschool-patterns","thumbnails/preschool/math/patterns/preschool-patterns"),backHref:"topic.html?grade=Preschool&subject=Math&topic=Patterns",backLabel:"Back to Patterns"},
  {id:"preschool-measurement",title:"Preschool Measurement & Comparing",description:"Compare length, height, size, amounts, and biggest or smallest.",grade:"Preschool",subject:"Math",topic:"Measurement & Comparing",skill:"Measurement",keywords:["measurement","long","short","tall","big","small","more water","biggest","smallest","compare"],pdfPath:"worksheets/preschool/math/measurement/preschool-measurement.pdf",thumbnailPath:"thumbnails/preschool/math/measurement/preschool-measurement/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/measurement/preschool-measurement","thumbnails/preschool/math/measurement/preschool-measurement"),backHref:"topic.html?grade=Preschool&subject=Math&topic=Measurement%20%26%20Comparing",backLabel:"Back to Measurement & Comparing"},
  {id:"preschool-sorting-data",title:"Preschool Sorting & Data",description:"Sort by kind and size, match groups, and read simple picture graphs.",grade:"Preschool",subject:"Math",topic:"Sorting & Data",skill:"Sorting & Data",keywords:["sorting","sort by kind","sort by size","classify","groups","match groups","picture graph","data","count and compare"],pdfPath:"worksheets/preschool/math/sorting/preschool-sorting-data.pdf",thumbnailPath:"thumbnails/preschool/math/sorting/preschool-sorting-data/page-01.png",pageCount:5,pages:defineWorksheetPages(5,"worksheets/preschool/math/sorting/preschool-sorting-data","thumbnails/preschool/math/sorting/preschool-sorting-data"),backHref:"topic.html?grade=Preschool&subject=Math&topic=Sorting%20%26%20Data",backLabel:"Back to Sorting & Data"}
];
const preschoolMathResourceSeoMetadata=Object.freeze({
  "trace-numbers-1-20":{seoTitle:"Trace Numbers 1-20 Printable | Learning Made Simple",seoDescription:"Free printable preschool worksheet for tracing numbers 1 through 20 in a clear, spacious grid."},
  "missing-numbers-1-20":{seoTitle:"Missing Numbers 1-20 Worksheet | Learning Made Simple",seoDescription:"Printable preschool number-order practice with simple sequences and missing numbers from 1 through 20."},
  "connect-the-dots-1-20":{seoTitle:"Connect the Dots 1-20 Worksheet | Learning Made Simple",seoDescription:"A printable preschool counting worksheet where children connect numbered dots from 1 to 20 to complete a rocket."},
  "number-recognition-1-5":{seoTitle:"Number Recognition 1-5 Worksheets | Learning Made Simple",seoDescription:"Printable preschool worksheets for recognizing, finding, counting, and tracing the numbers 1 through 5."},
  "number-recognition-6-10":{seoTitle:"Number Recognition 6-10 Worksheets | Learning Made Simple",seoDescription:"Printable preschool worksheets for recognizing, finding, counting, and tracing the numbers 6 through 10."},
  "number-recognition-11-15":{seoTitle:"Number Recognition 11-15 Worksheets | Learning Made Simple",seoDescription:"Printable preschool worksheets for recognizing, finding, counting, and tracing the numbers 11 through 15."},
  "number-recognition-16-20":{seoTitle:"Number Recognition 16-20 Worksheets | Learning Made Simple",seoDescription:"Printable preschool worksheets for recognizing, finding, counting, and tracing the numbers 16 through 20."},
  "counting-objects-1-5":{seoTitle:"Counting Objects 1-5 Worksheets | Learning Made Simple",seoDescription:"Preschool counting worksheets with picture groups and quantities from 1 through 5 to count, match, write, and draw."},
  "counting-objects-1-10":{seoTitle:"Counting Objects 1-10 Worksheets | Learning Made Simple",seoDescription:"Printable preschool activities for counting picture groups and working with quantities from 1 through 10."},
  "counting-objects-11-20":{seoTitle:"Counting Objects 11-20 Worksheets | Learning Made Simple",seoDescription:"Printable preschool counting practice with picture groups and quantities from 11 through 20."},
  "number-order-1-10":{seoTitle:"Number Order 1-10 Worksheets | Learning Made Simple",seoDescription:"Preschool worksheets for putting numbers 1 through 10 in order and finding numbers that come before, after, or between."},
  "number-order-11-20":{seoTitle:"Number Order 11-20 Worksheets | Learning Made Simple",seoDescription:"Preschool worksheets for ordering numbers 11 through 20 and completing before, after, and missing-number activities."},
  "more-fewer-same-1-10":{seoTitle:"More, Fewer & Same to 10 Worksheets | Learning Made Simple",seoDescription:"Printable preschool worksheets for comparing picture groups within 10 as more, fewer, or the same."},
  "addition-to-5":{seoTitle:"Preschool Addition to 5 Worksheets | Learning Made Simple",seoDescription:"Printable picture-based preschool worksheets for combining groups and practicing addition with totals up to 5."},
  "subtracting-within-5":{seoTitle:"Preschool Subtraction Within 5 Worksheets | Learning Made Simple",seoDescription:"Printable preschool worksheets for taking away, crossing out, and solving picture subtraction within 5."},
  "addition-facts-within-5":{seoTitle:"Addition Facts Within 5 Worksheets | Learning Made Simple",seoDescription:"Preschool practice with horizontal and vertical addition equations and facts with sums within 5."},
  "subtraction-facts-within-5":{seoTitle:"Subtraction Facts Within 5 Worksheets | Learning Made Simple",seoDescription:"Preschool practice with horizontal and vertical subtraction equations and facts within 5."},
  "simple-addition-subtraction-stories":{seoTitle:"Preschool Math Story Worksheets Within 5 | Learning Made Simple",seoDescription:"Picture-based preschool story problems for practicing simple addition and subtraction within 5."},
  "2d-shapes":{seoTitle:"Preschool 2D Shapes Worksheets | Learning Made Simple",seoDescription:"Printable preschool worksheets for recognizing, matching, tracing, and drawing circles, squares, triangles, and rectangles."},
  "3d-shapes":{seoTitle:"Preschool 3D Shapes Worksheets | Learning Made Simple",seoDescription:"Printable preschool worksheets for recognizing and matching spheres, cubes, cones, cylinders, and rectangular prisms."},
  "positional-words":{seoTitle:"Positional Words Worksheets for Preschool | Learning Made Simple",seoDescription:"Printable preschool activities for learning spatial words such as above, below, in, on, under, next to, and between."},
  "preschool-patterns":{seoTitle:"Preschool Pattern Worksheets | Learning Made Simple",seoDescription:"Free printable preschool worksheets for recognizing, continuing, copying, and creating simple repeating patterns."},
  "preschool-measurement":{seoTitle:"Preschool Measurement Worksheets | Learning Made Simple",seoDescription:"Printable preschool activities for comparing length, height, size, amounts, and biggest or smallest objects."},
  "preschool-sorting-data":{seoTitle:"Preschool Sorting & Data Worksheets | Learning Made Simple",seoDescription:"Printable preschool worksheets for sorting by kind or size, matching groups, and reading simple picture graphs."}
});
const preschoolReadingResourceSeoMetadata=Object.freeze({
  "learn-my-letters-a-z":{seoTitle:"Learn My Letters A-Z Worksheets | Learning Made Simple",seoDescription:"Free printable preschool alphabet worksheets for exploring uppercase and lowercase letters with pictures and letter hunts."},
  "trace-my-letters-a-z":{seoTitle:"Trace Letters A-Z Worksheets for Preschool | Learning Made Simple",seoDescription:"Printable preschool worksheets for tracing uppercase and lowercase letters and practicing letter formation from A to Z."},
  "match-big-little-letters-a-z":{seoTitle:"Uppercase & Lowercase Letter Matching | Learning Made Simple",seoDescription:"Printable preschool alphabet worksheets for matching uppercase letters with their lowercase partners from A to Z."},
  "abc-order-missing-letters":{seoTitle:"ABC Order & Missing Letters Worksheets | Learning Made Simple",seoDescription:"Printable preschool alphabet activities for practicing ABC order and filling in missing uppercase and lowercase letters."},
  "parts-of-a-book":{seoTitle:"Parts of a Book Worksheets for Preschool | Learning Made Simple",seoDescription:"Printable preschool activities for learning the front cover, back cover, title, author, and basic reading direction."},
  "beginning-sounds":{seoTitle:"Beginning Sounds Worksheets for Preschool | Learning Made Simple",seoDescription:"Printable preschool beginning-sound worksheets for listening to words and matching pictures with their starting letters."},
  "rhyming-pictures":{seoTitle:"Rhyming Pictures Worksheets for Preschool | Learning Made Simple",seoDescription:"Printable preschool rhyming worksheets for matching familiar pictures and identifying words that sound alike."},
  "clap-the-syllables":{seoTitle:"Clap the Syllables Worksheets | Learning Made Simple",seoDescription:"Printable preschool syllable activities for clapping and counting the word beats in familiar picture names."},
  "opposites":{seoTitle:"Opposites Worksheets for Preschool | Learning Made Simple",seoDescription:"Printable preschool vocabulary worksheets for exploring opposite words through familiar pictures and simple activities."},
  "categories":{seoTitle:"Categories Worksheets for Preschool | Learning Made Simple",seoDescription:"Printable preschool vocabulary activities for grouping familiar objects and understanding what different items are used for."},
  "story-comprehension":{seoTitle:"Story & Comprehension Printable Pack | Learning Made Simple",seoDescription:"A five-page printable preschool pack with picture questions, sequencing, prediction, and beginning-middle-end activities."}
});
const preschoolMathTopicSeoMetadata=Object.freeze({
  "Shapes & Spatial Skills":{title:"Preschool Shapes & Spatial Skills Worksheets | Learning Made Simple",description:"Printable preschool worksheets for 2D shapes, 3D shapes, and positional words such as above, below, beside, and between."},
  "Patterns":{title:"Free Preschool Pattern Worksheets | Learning Made Simple",description:"Free printable preschool pattern worksheets for recognizing, continuing, copying, and creating repeating patterns."},
  "Measurement & Comparing":{title:"Preschool Measurement & Comparing Worksheets | Learning Made Simple",description:"Printable preschool worksheets for comparing length, height, size, amounts, and biggest or smallest objects."},
  "Sorting & Data":{title:"Preschool Sorting & Data Worksheets | Learning Made Simple",description:"Printable preschool activities for sorting objects, matching groups, and reading simple picture graphs."}
});
const preschoolReadingTopicSeoMetadata=Object.freeze({
  "Alphabet":{title:"Free Preschool Alphabet Worksheets | Learning Made Simple",description:"Free printable preschool alphabet worksheets for letter recognition, tracing, uppercase and lowercase matching, and ABC order."},
  "Print Awareness":{title:"Print Awareness Worksheets for Preschool | Learning Made Simple",description:"Printable preschool activities for learning parts of a book, how print works, and the direction we read."},
  "Sounds & Beginning Phonics":{title:"Preschool Beginning Sounds & Phonics Worksheets | Learning Made Simple",description:"Printable preschool worksheets for hearing beginning sounds and connecting familiar pictures with starting letters."},
  "Rhymes & Word Beats":{title:"Preschool Rhyming & Syllable Worksheets | Learning Made Simple",description:"Printable preschool activities for matching rhyming pictures and clapping syllables in familiar words."},
  "Words & Vocabulary":{title:"Preschool Vocabulary Worksheets | Learning Made Simple",description:"Printable preschool vocabulary worksheets for learning opposites, sorting familiar objects into categories, and building word knowledge."},
  "Story & Comprehension":{title:"Preschool Story & Comprehension Worksheets | Learning Made Simple",description:"Printable preschool story worksheets for answering picture questions, sequencing events, making predictions, and retelling stories."}
});
const preschoolMathSkillSeoMetadata=Object.freeze({
  counting:{title:"Preschool Counting Worksheets | Learning Made Simple",description:"Printable preschool counting worksheets with picture groups, number quantities, and activities from 1 through 20."},
  "number-order":{title:"Preschool Number Order Worksheets | Learning Made Simple",description:"Printable preschool worksheets for number sequences, before and after numbers, and missing numbers from 1 through 20."},
  "more-fewer-same":{title:"More, Fewer & Same Preschool Worksheets | Learning Made Simple",description:"Printable preschool worksheets for comparing groups and identifying which has more, fewer, or the same amount."},
  addition:{title:"Preschool Addition & Subtraction Worksheets | Learning Made Simple",description:"Printable preschool worksheets for picture addition, subtraction, facts, and simple math stories within 5."}
});
const requiredWorksheetResourceFields=["id","title","grade","subject","topic","skill","keywords","pdfPath","thumbnailPath","pageCount","pages"];
window.worksheetAssetBaseUrl="https://assets.simplelearningresources.com";
const worksheetAssetBaseUrl=window.worksheetAssetBaseUrl||"";
const resolveWorksheetAssetUrl=(path,baseUrl=worksheetAssetBaseUrl)=>{
  if(typeof path!=="string"||!path)throw new Error("Worksheet asset path is required.");
  if(typeof baseUrl!=="string")throw new Error("Worksheet asset base URL must be a string.");
  return baseUrl?`${baseUrl.replace(/\/+$/,"")}/${path.replace(/^\/+/,"")}`:path;
};
const validateWorksheetAssetResolver=()=>{
  const path="worksheets/example.pdf";
  if(resolveWorksheetAssetUrl(path,"")!==path)throw new Error("Local worksheet asset URL resolution failed.");
  if(resolveWorksheetAssetUrl(path,"https://assets.example.com/library/")!=="https://assets.example.com/library/worksheets/example.pdf")throw new Error("Remote worksheet asset URL resolution failed.");
};
const validateWorksheetResources=(resources)=>{
  const ids=new Set();
  const pagePreviewPaths=new Set();
  const pagePdfPaths=new Set();
  if(resources.length!==39)throw new Error(`Expected 39 canonical worksheet resources, found ${resources.length}.`);
  resources.forEach((resource)=>{
    const missing=requiredWorksheetResourceFields.filter((field)=>resource[field]===undefined||resource[field]===null||resource[field]==="");
    if(missing.length)throw new Error(`Worksheet resource ${resource.id||"(missing id)"} is missing: ${missing.join(", ")}`);
    if(ids.has(resource.id))throw new Error(`Duplicate worksheet resource id: ${resource.id}`);
    if(!Array.isArray(resource.keywords)||!resource.keywords.length)throw new Error(`Worksheet resource ${resource.id} requires keywords.`);
    if(!Number.isInteger(resource.pageCount)||resource.pageCount<1)throw new Error(`Worksheet resource ${resource.id} has an invalid pageCount.`);
    if(!Array.isArray(resource.pages)||resource.pages.length!==resource.pageCount)throw new Error(`Worksheet resource ${resource.id} pages must match pageCount.`);
    resource.pages.forEach((page,index)=>{
      const expectedNumber=index+1;
      if(page.number!==expectedNumber)throw new Error(`Worksheet resource ${resource.id} has non-sequential page numbering.`);
      if(typeof page.previewPath!=="string"||!page.previewPath.endsWith(`/page-${String(expectedNumber).padStart(2,"0")}.png`))throw new Error(`Worksheet resource ${resource.id} page ${expectedNumber} has an invalid previewPath.`);
      if(typeof page.pdfPath!=="string"||!page.pdfPath.endsWith(`/page-${String(expectedNumber).padStart(2,"0")}.pdf`))throw new Error(`Worksheet resource ${resource.id} page ${expectedNumber} has an invalid pdfPath.`);
      if(pagePreviewPaths.has(page.previewPath))throw new Error(`Duplicate worksheet page preview path: ${page.previewPath}`);
      if(pagePdfPaths.has(page.pdfPath))throw new Error(`Duplicate worksheet page PDF path: ${page.pdfPath}`);
      pagePreviewPaths.add(page.previewPath);
      pagePdfPaths.add(page.pdfPath);
    });
    if(resource.thumbnailPath!==resource.pages[0].previewPath)throw new Error(`Worksheet resource ${resource.id} thumbnailPath must equal its first page previewPath.`);
    ids.add(resource.id);
  });
};
validateWorksheetAssetResolver();
validateWorksheetResources(worksheetResourceDefinitions);
const worksheetResources=Object.freeze(worksheetResourceDefinitions.map((resource)=>Object.freeze({...resource,...(preschoolMathResourceSeoMetadata[resource.id]||preschoolReadingResourceSeoMetadata[resource.id]||{}),keywords:Object.freeze(resource.keywords),pages:Object.freeze(resource.pages.map((page)=>Object.freeze({...page,previewUrl:resolveWorksheetAssetUrl(page.previewPath),pdfUrl:resolveWorksheetAssetUrl(page.pdfPath)}))),pdfUrl:resolveWorksheetAssetUrl(resource.pdfPath),thumbnailUrl:resolveWorksheetAssetUrl(resource.thumbnailPath),previewHref:`resource-preview.html?resource=${encodeURIComponent(resource.id)}`,meta:`${resource.grade} • ${resource.subject} • ${resource.topic} • ${resource.skill}`.toUpperCase()})));
const worksheetResourcesById=Object.freeze(Object.fromEntries(worksheetResources.map((resource)=>[resource.id,resource])));
const canonicalSiteOrigin="https://simplelearningresources.com";
const setIndexableCanonicalUrl=(relativeUrl)=>{
  const canonicalUrl=new URL(relativeUrl,`${canonicalSiteOrigin}/`).href;
  let canonicalLink=document.querySelector('link[rel="canonical"]');
  if(!canonicalLink){
    canonicalLink=document.createElement("link");
    canonicalLink.rel="canonical";
    document.head.append(canonicalLink);
  }
  canonicalLink.href=canonicalUrl;
  const robotsMeta=document.querySelector('meta[name="robots"]');
  if(robotsMeta)robotsMeta.content="index,follow";
  return canonicalUrl;
};
const setPageSeoMetadata=({title,description})=>{
  if(title)document.title=title;
  if(description){
    let descriptionMeta=document.querySelector('meta[name="description"]');
    if(!descriptionMeta){
      descriptionMeta=document.createElement("meta");
      descriptionMeta.name="description";
      document.head.append(descriptionMeta);
    }
    descriptionMeta.content=description;
  }
};
const normalizeResourceSearchValue=(value)=>String(value||"").trim().toLowerCase();
const searchWorksheetResources=({query="",grade="",subject="",topic="",skill=""}={})=>{
  const queryValue=normalizeResourceSearchValue(query);
  const filters={grade,subject,topic,skill};
  return worksheetResources.filter((resource)=>
    Object.entries(filters).every(([field,value])=>!value||normalizeResourceSearchValue(resource[field])===normalizeResourceSearchValue(value))&&
    (!queryValue||[resource.title,resource.grade,resource.subject,resource.topic,resource.skill,...resource.keywords].some((value)=>normalizeResourceSearchValue(value).includes(queryValue)))
  );
};
window.worksheetResources=worksheetResources;
window.worksheetResourcesById=worksheetResourcesById;
window.searchWorksheetResources=searchWorksheetResources;
window.resolveWorksheetAssetUrl=resolveWorksheetAssetUrl;
window.setIndexableCanonicalUrl=setIndexableCanonicalUrl;
window.setPageSeoMetadata=setPageSeoMetadata;
window.preschoolMathTopicSeoMetadata=preschoolMathTopicSeoMetadata;
window.preschoolReadingTopicSeoMetadata=preschoolReadingTopicSeoMetadata;
window.preschoolMathSkillSeoMetadata=preschoolMathSkillSeoMetadata;

const renderDirectory = () => {
  const subjectNames={math:"Math",reading:"Reading & Language",communication:"Communication & Life Skills",science:"Science & Discovery",thinking:"Thinking & Our World"};
  const grades={preschool:"Preschool",kindergarten:"Kindergarten","grade-1":"Grade 1","grade-2":"Grade 2"};
  const numbersCountingSkills=[
    {title:"Number Recognition",description:"Recognize, find, count, and trace numbers.",href:"number-recognition.html"},
    {title:"Counting",description:"Count objects and connect groups to quantities.",href:"skill-directory.html?skill=counting"},
    {title:"Number Order",description:"Put numbers in order and find missing numbers.",href:"skill-directory.html?skill=number-order"},
    {title:"More, Fewer & Same",description:"Compare groups using visual quantities.",href:"skill-directory.html?skill=more-fewer-same"},
    ...["trace-numbers-1-20", "missing-numbers-1-20", "connect-the-dots-1-20"].map(id=>{
      const resource=worksheetResourcesById[id];
      return {title:resource.title,description:resource.description,href:resource.previewHref};
    })
  ];
  const preschoolMathSkills=[
    ...numbersCountingSkills,
    {title:"Early Addition & Subtraction",description:"Put groups together and take groups apart.",href:"skill-directory.html?skill=addition"},
    {title:"Patterns",description:"Meet repeating patterns, find what comes next, and create simple shape patterns.",href:"topic.html?grade=Preschool&subject=Math&topic=Patterns"},
    {title:"Measurement & Comparing",description:"Compare length, height, size, amounts, and biggest or smallest.",href:"topic.html?grade=Preschool&subject=Math&topic=Measurement%20%26%20Comparing"},
    {title:"Sorting & Data",description:"Sort by kind and size, match groups, and read simple picture graphs.",href:"topic.html?grade=Preschool&subject=Math&topic=Sorting%20%26%20Data"}
  ];
  const data={
    math:{preschool:"Numbers & Counting|Early Addition & Subtraction|Shapes & Spatial Skills|Patterns|Measurement & Comparing|Sorting & Data",kindergarten:"Numbers & Counting|Addition|Subtraction|Shapes & Geometry|Patterns|Measurement|Sorting & Data","grade-1":"Numbers & Place Value|Addition|Subtraction|Measurement|Time|Shapes & Fractions|Data & Graphing|Mathematical Thinking","grade-2":"Numbers & Place Value|Addition|Subtraction|Equal Groups & Arrays|Measurement|Time|Money|Data & Graphing|Geometry & Equal Shares"},
    reading:{preschool:"Alphabet|Print Awareness|Sounds & Beginning Phonics|Rhymes & Word Beats|Words & Vocabulary|Story & Comprehension|Early Writing",kindergarten:"Alphabet & Letter Formation|Phonological Awareness|Phonics|CVC Words|High-Frequency Words|Vocabulary|Sentences|Early Comprehension|Story Elements|Early Writing","grade-1":"Phonics & Word Reading|High-Frequency Words|Fluency|Vocabulary|Grammar & Sentences|Reading Comprehension|Story Elements|Informational Reading|Writing","grade-2":"Advanced Phonics|Fluency|Vocabulary|Grammar|Reading Comprehension|Literature|Informational Reading|Writing"},
    communication:{preschool:"Understanding Language|Expressing Needs & Ideas|WH Questions|Conversation & Play|Feelings & Social Understanding|Visual Supports & Routines|Independence & Safety",kindergarten:"Following Directions|WH Questions|Expressing Ideas|Conversation|Social Skills|Feelings & Regulation|Routines & Independence|Safety & Self-Advocacy","grade-1":"Following Directions|WH Questions|Describing & Explaining|Conversation|Social Communication|Emotions & Regulation|Independence|Self-Advocacy & Safety","grade-2":"Following Complex Directions|Asking & Answering Questions|Describing & Explaining|Conversation|Social Understanding|Emotional Problem Solving|Independence & Organization|Self-Advocacy & Safety"},
    science:{preschool:"Animals|Plants & Nature|Human Body & Five Senses|Weather & Seasons|Earth & Space|Living & Non-Living|Exploring Materials|Little Scientist",kindergarten:"Living Things|Plants|Animals|Human Body|Weather & Seasons|Earth & Sky|Materials & Motion|Scientific Thinking","grade-1":"Plants & Animals|Human Body & Health|Earth & Space|Weather|Materials & Motion|Scientific Thinking","grade-2":"Plants & Animals|Habitats & Life Cycles|Earth & Environment|Weather|Matter & Materials|Forces & Motion|Light & Sound|Scientific Thinking"},
    thinking:{preschool:"Logic & Matching|Myself & Family|Community|Maps & Places|Time & Sequence",kindergarten:"Logic & Problem Solving|Myself & Family|Community|Maps & Places|Past & Present|Needs & Wants","grade-1":"Logic & Reasoning|Families & Communities|Maps & Geography|Past & Present|Needs & Wants|Culture & Our World","grade-2":"Logic & Reasoning|Communities|Maps & Geography|Past & Present|Economics|People & Culture"}
  };
  const file=location.pathname.split("/").pop()||"index.html";
  const subjects={"math.html":"math","reading.html":"reading","communication.html":"communication","science.html":"science","thinking-world.html":"thinking"};
  const gradeFiles={"preschool.html":"preschool","kindergarten.html":"kindergarten","grade-1.html":"grade-1","grade-2.html":"grade-2"};
  const topicLink=(grade,subject,topic)=>grade==="preschool"&&subject==="math"&&topic==="Numbers & Counting"?"numbers-counting.html":grade==="preschool"&&subject==="math"&&topic==="Early Addition & Subtraction"?"skill-directory.html?skill=addition":"topic.html?grade="+encodeURIComponent(grades[grade])+"&subject="+encodeURIComponent(subjectNames[subject])+"&topic="+encodeURIComponent(topic);
  const block=(grade,subject)=>`<div class="directory-section"><h2>${grades[grade]}</h2><ul>${data[subject][grade].split("|").map(topic=>`<li><a href="${topicLink(grade,subject,topic)}">${topic}</a></li>`).join("")}</ul></div>`;
  const skillMarkup=(skills)=>`<div class="directory-grid skill-family-grid">${skills.map(skill=>`<div><h2><a href="${skill.href}">${skill.title}</a></h2><p>${skill.description}</p></div>`).join("")}</div>`;
  const library=document.querySelector("section.library");
  if(!library)return;
  if(subjects[file]){const subject=subjects[file];document.title=subject==="math"?"Free Preschool Math Worksheets | Learning Made Simple":subject==="reading"?"Free Preschool Reading Worksheets | Learning Made Simple":`${subjectNames[subject]} | Learning Made Simple`;library.innerHTML=subject==="math"?`<div class="library-header"><p class="eyebrow">PRESCHOOL MATH</p><h1>Math Worksheets</h1><p>Browse current preschool math skills.</p></div>${skillMarkup(preschoolMathSkills)}`:`<div class="library-header"><p class="eyebrow">RESOURCE DIRECTORY</p><h1>${subjectNames[subject]}</h1><p>Browse topics by grade.</p></div><div class="directory-grid subject-directory">${Object.keys(grades).map(grade=>block(grade,subject)).join("")}</div>`;}
  if(gradeFiles[file]){const grade=gradeFiles[file];document.title=grade==="preschool"?"Preschool Learning Resources | Learning Made Simple":`${grades[grade]} | Learning Made Simple`;library.innerHTML=`<div class="library-header"><p class="eyebrow">GRADE DIRECTORY</p><h1>${grades[grade]}</h1><p>Browse resources by subject.</p></div><div class="directory-grid grade-directory">${Object.keys(subjectNames).map(subject=>`<div class="directory-section" id="${subject}"><h2>${subjectNames[subject]}</h2><ul>${data[subject][grade].split("|").map(topic=>`<li><a href="${topicLink(grade,subject,topic)}">${topic}</a></li>`).join("")}</ul></div>`).join("")}</div>`;}
  if(file==="numbers-counting.html"){document.title="Preschool Numbers & Counting Worksheets | Learning Made Simple";library.innerHTML=`<div class="library-header"><p class="eyebrow">PRESCHOOL &bull; MATH</p><h1>Numbers &amp; Counting</h1><p>Choose a number skill family.</p></div>${skillMarkup(numbersCountingSkills)}`;}
};
if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", renderDirectory); else renderDirectory();
